title: blog.qsh.io
author: Downet
email: downet@protonmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Gandalfův zápisník o Bitcoinu a Lightning network.
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/blog/page:num/"

# tag_permalink_style: pretty
# tag_page_layout: tag_page
# tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%-D"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://donate.qsh.io
      icon: btc
      color: yellow
    - url: https://discord.com/invite/HWG9Erm
      icon: discord
      color: purple
    - url: https://github.com/downet
      icon: github-square
      color: green

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
# - jekyll/tagging

# Replaces the default avatar provider (gravatar)
avatar_source: github
github_username: downet
